name: coody
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  another_stepper: ^1.2.2
  bloc: ^8.1.2
  built_value: ^8.9.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.15.3
  dropdown_model_list: ^2.0.2
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.9
  flutter_zoom_drawer: ^3.1.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.6
  intl: ^0.19.0
  lottie: ^3.0.0
  mask_text_input_formatter: ^2.8.0
  scrollable_list_tab_scroller: ^1.1.2
  select_searchable_list: ^0.1.5
  shaky_animated_listview: ^0.0.5
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timeago: ^3.6.1
  u_credit_card: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
